### ISSUE TITLE
Recommend Papers to Read

### ISSUE THREAD

**Issue by dexhunter** [PremiLab-XJTLU/Meeting#1]
@LinkWoong please provide a list of papers to read (probably should add sth. to wiki).

eg. 
1. [DeLiGAN](https://arxiv.org/abs/1706.02071)

**Comment by LinkWoong** [comment]
Yes, thanks for your suggestion.

**Comment by dexhunter** [comment]
I see. Moved to [readme](https://github.com/PremiLab-XJTLU/Meeting/blob/master/Chenhui_Wang/Readme.md)

**Comment by dexhunter** [comment]
suggest reading: https://arxiv.org/pdf/1710.08347.pdf
